### ISSUE TITLE
SyntaxError: Module build failed

### ISSUE THREAD

**Issue by jasonlimantoro** [yutahaga/tailwindcss-pseudo-elements#3]
I use `tailwindcss` along with Storybook to work on my own Styleguide.
When I realize I need pseudo class selector, I decided to use this plugin.
After copying the docs, when reloading the storybook, I got the following errors:

```javascript
ERROR in ./src/index.scss (./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js!./src/index.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
./node_modules/tailwindcss-pseudo-elements/index.js:4
  const escape = e || x => x
                   ^^

SyntaxError: Unexpected token ||
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/jasonlimantoro/code/web/appointment_custom/tailwind.config.js:67:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
 @ ./src/index.scss 2:14-134 21:1-42:3 22:19-139
 @ ./.storybook/config.js
```

Any ideas?

**Comment by yutahaga** [comment]
Thanks to your report, we were able to fix syntax errors quickly.
The problem was fixed in v1.1.1.
